### ISSUE TITLE
Error label is confusing on login

### ISSUE THREAD

**Issue by Andriew** [polski-dev/frontend.blog#8]
![image](https://user-images.githubusercontent.com/6099998/181845650-2075522e-f237-4663-88c7-c94ed47fc7e0.png)
Text on error label is confusing. 
I didn't have registered account but text tells me "There's a problem". I didn't know that there is a problem with login or some internal service problem.

**Comment by pawel-niedzwiecki** [comment]
Ok now you can try again ? :)

**Comment by Andriew** [comment]
seems to be ok
